### ISSUE TITLE
SSE3 tracker

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/lokacore#13]
* [x] _mm_addsub_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_addsub_ps(__m128 a, __m128 b) -> __m128
* [x] _mm_hadd_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_hadd_ps(__m128 a, __m128 b) -> __m128
* [x] _mm_hsub_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_hsub_ps(__m128 a, __m128 b) -> __m128
* [x] _mm_lddqu_si128(__m128i const* mem_addr) -> __m128i
* [x] _mm_loaddup_pd(double const* mem_addr) -> __m128d
* [x] _mm_movedup_pd(__m128d a) -> __m128d
* [x] _mm_movehdup_ps(__m128 a) -> __m128
* [x] _mm_moveldup_ps(__m128 a) -> __m128
